---
blank_issues_enabled: false
contact_links:
  - name: Security Policy
    url: https://github.com/Lipford-Dutch/Dev-System-Awesome/security/policy
    about: Report vulnerabilities using the security policy.
